{{- if and (eq .Values.storage.type "s3") (not .Values.storage.s3.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pbs-cloud.s3SecretName" . }}
  labels:
    {{- include "pbs-cloud.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.storage.s3.accessKeyIdKey }}: {{ .Values.storage.s3.accessKeyId | b64enc | quote }}
  {{ .Values.storage.s3.secretAccessKeyKey }}: {{ .Values.storage.s3.secretAccessKey | b64enc | quote }}
{{- end }}
